services:
  binly:
    build: .
    restart: unless-stopped
    environment:
      # Generate a random hex string for production: openssl rand -hex 32
      - APP_SECRET=${APP_SECRET:-super_long_random_hex}
    ports:
      - "7700:8080"
    volumes:
      - ./data:/app/data
