services:
  binly:
    build: .
    restart: unless-stopped
    environment:
      - APP_SECRET=super_long_random_hex
    ports:
      - "80:8080"
      - "127.0.0.1:8787:8787"
    volumes:
      - ./data:/app/data
